### ISSUE TITLE
Forward slash ("/") gets replaced by ("\\") when executing on windows 11

### ISSUE THREAD

**Issue by draner** [PrefectHQ/prefect-gcp#116]
Hi everyone, i'm having an issue with prefect on windows.
We've bumped into an issue that prefect-gcp is actually converting the / (forward slashes) into \\ double backward slashes during the upload tasks,
Which translates into the blob being named, for example, as:
` foo\\bar\\foobar.txt`
Instead of actually:
`foo/bar/foobar.txt `
Which would be represented as "folders" in the GCS Web interface.
We're not sure if the same issue happens on macOS or Linux
We've tried not only the upload_from_path but also the upload_from_file_object.
Here's the full task in question : 
```python
@task(log_prints=True)
def write_gcs(path: Path) -> None:
    """Write data to GCS."""
    gcp_cloud_storage_bucket_block = GcsBucket.load("gcs-de-zoomcamp")
    print(f"Writing {path} to GCS")
    gcp_cloud_storage_bucket_block.upload_from_path(from_path= path, to_path= path)
    return
```
the variable path is created earlier as `path = Path(f"data/{color}/{dataset_file}.parquet")`

i've tried the following : 
- removing `to_path`
- passing the path as a string (`str(path)`)

I think part of the solution is that we need to pass the `Path.as_posix()` when Prefect is executed from windows so that it become os agnostic but i could be wrong
Thanks in advance for any feedback

**Comment by draner** [comment]
The PR is fixing the problem for me, as long as you specify that you want `path = Path(path).as_posix()` everything is fine.
Should i close the issue ? I'm not used to the rules regarding Issues on Github

**Comment by discdiver** [comment]
Thank you for the confirmation @draner! You don't need to close the issue. It will be closed when the fix is merged. 🙂
