### ISSUE TITLE
GcsBucket#get_directory should return the list of paths of downloaded files

### ISSUE THREAD

**Issue by saint1991** [PrefectHQ/prefect-gcp#127]
# Proposal

GcsBucket#get_directory should return the list of paths of downloaded files because this is the only way to know which files are newly downloaded from downstream tasks.

# Example

Its signature may become like 

```
async def get_directory(self, from_path: Optional[str] = None, local_path: Optional[str] = None ) -> List[Union[str, Path]]
```

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-gcp/#contributing) a pull request to resolve this!

**Comment by ahuang11** [comment]
Closed by https://github.com/PrefectHQ/prefect-gcp/pull/129

Thank you!
