### ISSUE TITLE
Vertex AI Custom Training Job does not show up as a Block option in the UI

### ISSUE THREAD

**Issue by salman1993** [PrefectHQ/prefect-gcp#130]
# Expectation / Proposal
`VertexAICustomTrainingJob` inherits from `Infrastructure` and also has the block slug name & type so I was expecting it to show up as an option when you go to the "Cloud UI > Blocks > Add Block". However, there is no infrastructure block option for Vertex AI (screenshot). 

https://github.com/PrefectHQ/prefect-gcp/blob/28b45694210b7d2e5765a2743be5f35bfb5f826a/prefect_gcp/aiplatform.py#L98

![Screen Shot 2023-02-03 at 8 56 16 AM](https://user-images.githubusercontent.com/7154255/216621257-73e1ee68-697a-41c0-b765-ad7e79e56617.png)

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-gcp/#contributing) a pull request to resolve this!

**Comment by ahuang11** [comment]
Have you registered the block?
`prefect block register -m prefect_gcp`

**Comment by salman1993** [comment]
This worked! Thank you!
