### ISSUE TITLE
Fix Official Docs on upload_from_dataframe

### ISSUE THREAD

**Issue by iobruno** [PrefectHQ/prefect-gcp#163]
# Expectation / Proposal
It was recently [noticed on DataTalksClub's Slack](https://datatalks-club.slack.com/archives/C01FABYF2RG/p1680376904693889?thread_ts=1676507721.776929&cid=C01FABYF2RG) that, the [official documentation for upload_from_dataframe](https://prefecthq.github.io/prefect-gcp/cloud_storage/#prefect_gcp.cloud_storage.GcsBucket.upload_from_dataframe) states that, among other options, `parquet_gz` is valid, which is inaccurate, as it should be `parquet_gzip`.

Since the MkDocs is generated from the method docstring:
![image](https://user-images.githubusercontent.com/901651/229560906-45820815-9c95-4f18-9936-2cc3a4c971b7.png)

I propose that we fix the documentation to avoid further errors or confusion by the user base.

# Traceback / Example

```python
import pandas as pd
from prefect_gcp.cloud_storage import GcsBucket

pandas_df = pd.read_csv(url="some_url")

gcs_bucket = GcsBucket.load("my-bucket")
gcs_bucket.upload_from_dataframe(
   df=pandas_df, 
   to_path="/path/to/gcs/blob.parquet", 
   serialization_format='parquet_gz'
)
```

Leads to `KEY_ERROR` as `parquet_gz` is not valid as the documentation suggests it to be.

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-gcp/#contributing) a pull request to resolve this!

**Comment by madkinsz** [comment]
Closed by #162
