### ISSUE TITLE
`list_blobs` and `list_folder` log incorrect bucket name

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-gcp#184]
# Expectation / Proposal

The `list_blobs` and `list_folder` methods on `GcsBucket` log what bucket and path they are listing blobs or folders for.

# Traceback / Example

When running this code:
```python
from prefect_gcp import GcsBucket

bucket = GcsBucket(
    bucket="my-bucket",
)

bucket.list_folders()
```

The log output is:
```
08:30:20.932 | INFO    | prefect.GcsBucket - Listing folders in bucket None.
08:30:21.002 | INFO    | prefect.GcsBucket - Listing blobs in bucket None.
```

Instead, the log messages should be:
```
08:30:20.932 | INFO    | prefect.GcsBucket - Listing folders in bucket 'my-bucket'.
08:30:21.002 | INFO    | prefect.GcsBucket - Listing blobs in bucket 'my-bucket`.
```

When running this code:
```python
from prefect_gcp import GcsBucket

bucket = GcsBucket(
    bucket="my-bucket",
    bucket_folder="my-folder",
)

bucket.list_folders()
```

The log output is:
```
08:30:20.932 | INFO    | prefect.GcsBucket - Listing folders in bucket my-folder.
08:30:21.002 | INFO    | prefect.GcsBucket - Listing blobs in bucket my-folder.
```

Instead, the log messages should be something like:
```
08:30:20.932 | INFO    | prefect.GcsBucket - Listing folders in folder 'my-folder' in bucket 'my-bucket'.
08:30:21.002 | INFO    | prefect.GcsBucket - Listing blobs in folder 'my-folder' in bucket 'my-bucket`.
```
- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-gcp/#contributing) a pull request to resolve this!

**Comment by bjarneschroeder** [comment]
Hey @desertaxle , if this is till an issue, I would love to help and contribute a PR. The provided link to the contribution-section of the library just refers to the starting page though. Did the section move to anywhere else? :)

**Comment by desertaxle** [comment]
Thanks for your willingness to contribute @bjarneschroeder! Thanks for letting us know that our contributing link needs to be updated. You can see our contribution guide here: https://prefecthq.github.io/prefect-gcp/contributing/.
