### ISSUE TITLE
Add "gs://" to bucket path if it's not present

### ISSUE THREAD

**Issue by peytonrunyan** [PrefectHQ/prefect-gcp#45]
The cloud storage block currently asks for a bucket path. If you click on "copy the path to the clipboard" it will give you just the bucket name. If you provide just the bucket name to the block, you will get the error `gcsfs.retry.HttpError: Invalid bucket name: <bucket_name>`. If you then rename the path to `gs://<bucket_name>` it will work. 

We should be able to handle this case without raising an error.

**Comment by ahuang11** [comment]
To clarify, did you mean this PR?
https://github.com/PrefectHQ/prefect-gcp/pull/41/files

**Comment by ahuang11** [comment]
Or did you mean
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L470

Also, does `gs://` and `gcs://` both work?

**Comment by peytonrunyan** [comment]
Excellent question! I keep forgetting that we have two different buckets. I'll have to double check but I'm pretty sure I actually meant the core Prefect bucket. And I'll  check on gs:// and gcs://

**Comment by ahuang11** [comment]
If I'm not mistaken, I think this applies to GCS in the core library. Can you open an issue there if this is still applicable?
