### ISSUE TITLE
Add External Table options for bigquery_create_table

### ISSUE THREAD

**Issue by Kevin-Grismore** [PrefectHQ/prefect-gcp#52]
It would be really awesome if the `bigquery_create_table` task supported options to build an `ExternalConfig` so we could define our BigQuery table as an external table. I made an attempt to write a version of this task in my own project, and it works for my needs, but doesn't cover all the available options for external tables.

```
@task
async def bigquery_create_table(
    dataset: str,
    table: str,
    gcp_credentials: "GcpCredentials",
    schema: List[SchemaField] = None,
    clustering_fields: List[str] = None,
    time_partitioning: TimePartitioning = None,
    project: Optional[str] = None,
    location: str = "US",
    external_config: Dict = None,
) -> str:
    """
    Creates table in BigQuery.
    Args:
        dataset: Name of a dataset in that the table will be created.
        table: Name of a table to create.
        schema: Schema to use when creating the table.
        gcp_credentials: Credentials to use for authentication with GCP.
        clustering_fields: List of fields to cluster the table by.
        time_partitioning: `bigquery.TimePartitioning` object specifying a partitioning
            of the newly created table
        project: Project to initialize the BigQuery Client with; if
            not provided, will default to the one inferred from your credentials.
        location: location of the dataset that will be written to.
        external_config: Source format, source uris, and additional settings.
    Returns:
        Table name.
    Example:
        ```python
        from prefect import flow
        from prefect_gcp import GcpCredentials
        from prefect_gcp.bigquery import bigquery_create_table
        from google.cloud.bigquery import SchemaField
        @flow
        def example_bigquery_create_table_flow():
            gcp_credentials = GcpCredentials(project="project")
            schema = [
                SchemaField("number", field_type="INTEGER", mode="REQUIRED"),
                SchemaField("text", field_type="STRING", mode="REQUIRED"),
                SchemaField("bool", field_type="BOOLEAN")
            ]
            result = bigquery_create_table(
                dataset="dataset",
                table="test_table",
                schema=schema,
                gcp_credentials=gcp_credentials
            )
            return result
        example_bigquery_create_table_flow()
        ```
    """
    logger = get_run_logger()
    logger.info("Creating %s.%s", dataset, table)

    client = gcp_credentials.get_bigquery_client(project=project, location=location)
    try:
        partial_get_dataset = partial(client.get_dataset, dataset)
        dataset_ref = await to_thread.run_sync(partial_get_dataset)
    except NotFound:
        logger.debug("Dataset %s not found, creating", dataset)
        partial_create_dataset = partial(client.create_dataset, dataset)
        dataset_ref = await to_thread.run_sync(partial_create_dataset)

    table_ref = dataset_ref.table(table)
    try:
        partial_get_table = partial(client.get_table, table_ref)
        await to_thread.run_sync(partial_get_table)
        logger.info("%s.%s already exists", dataset, table)
    except NotFound:
        logger.debug("Table %s not found, creating", table)

        table_obj = Table(table_ref, schema=schema)

        # external config stuff added here
        if external_config:
            external_data_configuration = ExternalConfig(
                external_config["source_format"]
            )

            external_data_configuration.source_uris = external_config["source_uris"]

            if external_config["hive_partitioning"]:
                hive_partitioning_options = HivePartitioningOptions()
                hive_partitioning_options.mode = external_config["hive_partitioning"][
                    "mode"
                ]
                hive_partitioning_options.source_uri_prefix = external_config[
                    "hive_partitioning"
                ]["source_uri_prefix"]
                hive_partitioning_options.require_partition_filter = external_config[
                    "hive_partitioning"
                ]["require_partition_filter"]
                external_data_configuration.hive_partitioning = (
                    hive_partitioning_options
                )

            if external_config["autodetect"]:
                external_data_configuration.autodetect = external_config["autodetect"]

            if external_config["source_format"] == "BIGTABLE":
                external_data_configuration.bigtable_options = external_config[
                    "bigtable_options"
                ]

            elif external_config["source_format"] == "CSV":
                external_data_configuration.csv_options = external_config["csv_options"]

            elif external_config["source_format"] == "GOOGLE_SHEETS":
                external_data_configuration.google_sheets_options = external_config[
                    "google_sheets_options"
                ]

            table_obj.external_data_configuration = external_data_configuration

        # cluster for optimal data sorting/access
        if clustering_fields:
            table_obj.clustering_fields = clustering_fields

        # partitioning
        if time_partitioning:
            table_obj.time_partitioning = time_partitioning

        partial_create_table = partial(client.create_table, table_obj)
        await to_thread.run_sync(partial_create_table)

    return table
```

**Comment by ahuang11** [comment]
Hi Kevin, thanks for sharing this!

I think to generalize, perhaps just an addition of `external_data_configuration` keyword argument could suffice, e.g.
```
@task
async def bigquery_create_table(
    dataset: str,
    table: str,
    schema: List[SchemaField],
    gcp_credentials: "GcpCredentials",
    clustering_fields: List[str] = None,
    time_partitioning: TimePartitioning = None,
    project: Optional[str] = None,
    location: str = "US",
    external_config: Optional[ExternalConfig] = None
) -> str:
    """
    Creates table in BigQuery.
    Args:
        dataset: Name of a dataset in that the table will be created.
        table: Name of a table to create.
        schema: Schema to use when creating the table.
        gcp_credentials: Credentials to use for authentication with GCP.
        clustering_fields: List of fields to cluster the table by.
        time_partitioning: `bigquery.TimePartitioning` object specifying a partitioning
            of the newly created table
        project: Project to initialize the BigQuery Client with; if
            not provided, will default to the one inferred from your credentials.
        location: The location of the dataset that will be written to.
        external_config: The [external data source](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#nested_external_data_configuration)
    Returns:
        Table name.
    Example:
        ```python
        from prefect import flow
        from prefect_gcp import GcpCredentials
        from prefect_gcp.bigquery import bigquery_create_table
        from google.cloud.bigquery import SchemaField
        @flow
        def example_bigquery_create_table_flow():
            gcp_credentials = GcpCredentials(project="project")
            schema = [
                SchemaField("number", field_type="INTEGER", mode="REQUIRED"),
                SchemaField("text", field_type="STRING", mode="REQUIRED"),
                SchemaField("bool", field_type="BOOLEAN")
            ]
            result = bigquery_create_table(
                dataset="dataset",
                table="test_table",
                schema=schema,
                gcp_credentials=gcp_credentials
            )
            return result
        example_bigquery_create_table_flow()
        ```
    """
    logger = get_run_logger()
    logger.info("Creating %s.%s", dataset, table)

    client = gcp_credentials.get_bigquery_client(project=project, location=location)
    try:
        partial_get_dataset = partial(client.get_dataset, dataset)
        dataset_ref = await to_thread.run_sync(partial_get_dataset)
    except NotFound:
        logger.debug("Dataset %s not found, creating", dataset)
        partial_create_dataset = partial(client.create_dataset, dataset)
        dataset_ref = await to_thread.run_sync(partial_create_dataset)

    table_ref = dataset_ref.table(table)
    try:
        partial_get_table = partial(client.get_table, table_ref)
        await to_thread.run_sync(partial_get_table)
        logger.info("%s.%s already exists", dataset, table)
    except NotFound:
        logger.debug("Table %s not found, creating", table)
        table_obj = Table(table_ref, schema=schema)

        # external data configuration
        if external_config:
            table_obj.external_data_configuration = external_config

        # cluster for optimal data sorting/access
        if clustering_fields:
            table_obj.clustering_fields = clustering_fields

        # partitioning
        if time_partitioning:
            table_obj.time_partitioning = time_partitioning

        partial_create_table = partial(client.create_table, table_obj)
        await to_thread.run_sync(partial_create_table)

    return table
```

Would you be interested in contributing a PR?

**Comment by Kevin-Grismore** [comment]
Sure! The only thing I was uncertain about is that if the external config's `autodetect` is `True` and the autodetect works, then providing a schema isn't necessary. I'm not sure what the behavior is if the autodetect fails, or whether it's completely clear to the user what will happen if they provide a schema and have autodetect enabled for their external table too. That's why I did `schema: List[SchemaField] = None`. Opinions?

**Comment by ahuang11** [comment]
Good point! Yes I think it can be `schema: Optional[List[SchemaField]] = None`, but ensure that `if not external_config and not schema: raise ValueError(...)`

**Comment by Kevin-Grismore** [comment]
From [Google's docs on the feature](https://cloud.google.com/bigquery/docs/schema-detect#schema_auto-detection_for_external_data_sources):

> Schema auto-detection can be used with CSV, JSON, and Sheets external data sources. When schema auto-detection is enabled, BigQuery makes a best-effort attempt to automatically infer the schema from the source data. If you don't enable schema auto-detection for these sources, then you must provide an explicit schema.

>You don't need to enable schema auto-detection when you query external Avro, Parquet, ORC, Firestore export, or Datastore export files. These file formats are self-describing, so BigQuery automatically infers the table schema from the source data. For Parquet, Avro, and Orc files, you can optionally provide an explicit schema to override the inferred schema.

I'll come back around to this in a little bit and see what happens if I try to autodetect with a messy csv.

**Comment by Kevin-Grismore** [comment]
Okay, revisiting this! I tried uploading a CSV with some very messy data like empty columns and mixed types, and making an external table, and when the data type of a column can't be interpreted from the values, it is defaulted to a String. So I don't think autodetect failures are something to worry about, if they're even possible.

I'll open a PR with all the suggested changes.

**Comment by ahuang11** [comment]
Thank you for exploring and reporting back the results! Really appreciate it!

**Comment by Kevin-Grismore** [comment]
It looks like I don't have permission to create a branch on this repo.

**Comment by ahuang11** [comment]
Right. Are you able to fork the repo, clone that repo, and push to that repo?

Once it's pushed to that repo, you can make a PR with this repo.

**Comment by Kevin-Grismore** [comment]
Oh! Yes I can. Sorry, this is my first contribution to an open source project 🥲

**Comment by ahuang11** [comment]
No worries, glad you're here to help improve prefect-gcp!
