### ISSUE TITLE
Document CloudRunJob better in README

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect-gcp#62]
It's currently:
- missing install cloud run
- how to register CloudRunJob block.

**Comment by davidschrooten** [comment]
Actually the cloud run job block is the most interesting feature of prefect 2.x. As it works similar to how vertex works in prefect 1.x; and provides an actual serverless environment to run pipelines in which is extremely powerful. Would be nice if this pip package can easily be added without building a custom prefect image.

**Comment by ahuang11** [comment]
Thanks for providing this feedback. To clarify, would [using `EXTRA_PIP_PACKAGES`](https://discourse.prefect.io/t/do-prefect-base-images-include-extras-from-the-task-library-e-g-postgres-for-the-postgres-tasks/437#h-1-installing-extra-dependencies-at-runtime-1) work for you?
