### ISSUE TITLE
Make `service_account_info` on the `GcpCredentials` block a `SecretStr` type

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect-gcp#73]
Currently, the value is not a secret string and can be viewed in plain text from the UI:

![image](https://user-images.githubusercontent.com/86264395/201557626-d9b6fba7-eb4e-4b3b-adf3-0cfa509d2b64.png)

if that's intended, please close the issue

**Comment by ahuang11** [comment]
I think we're planning for a SecretDict type, but in the meantime, we can make it a SecretStr type.
https://github.com/PrefectHQ/prefect/issues/6735

**Comment by anna-geller** [comment]
interesting, so that would be essentially a custom data type that is a combination of an arbitrary number of str-SecretStr KV pairs? I wonder if nobody asked about it in the Pydantic repo before, perhaps worth contributing to pydantic?

**Comment by discdiver** [comment]
SecretStr as a fix for now would be great! 👍
